//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.WorkOrders.API.Context.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestFailures
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestFailures()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.WorkOrders.API.Context.Resources.RequestFailures", typeof(RequestFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record with specified identifier not found..
        /// </summary>
        public static string EntityNotFoundByIdentifier
        {
            get
            {
                return ResourceManager.GetString("EntityNotFoundByIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Header &apos;{0}&apos; has invalid value..
        /// </summary>
        public static string HeaderInvalidValue
        {
            get
            {
                return ResourceManager.GetString("HeaderInvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Header &apos;{0}&apos; required..
        /// </summary>
        public static string HeaderRequired
        {
            get
            {
                return ResourceManager.GetString("HeaderRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Header &apos;{0}&apos; has an unsupported value..
        /// </summary>
        public static string HeaderUnsupportedValue
        {
            get
            {
                return ResourceManager.GetString("HeaderUnsupportedValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query parameter &apos;{0}&apos; has invalid value..
        /// </summary>
        public static string QueryParameterInvalidValue
        {
            get
            {
                return ResourceManager.GetString("QueryParameterInvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Query paramater &apos;{0}&apos; required..
        /// </summary>
        public static string QueryParameterRequired
        {
            get
            {
                return ResourceManager.GetString("QueryParameterRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request body has invalid value..
        /// </summary>
        public static string RequestBodyInvalidValue
        {
            get
            {
                return ResourceManager.GetString("RequestBodyInvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request body required..
        /// </summary>
        public static string RequestBodyRequired
        {
            get
            {
                return ResourceManager.GetString("RequestBodyRequired", resourceCulture);
            }
        }
    }
}
