//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.WorkOrders.API.Context.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.WorkOrders.API.Context.Resources.ServiceErrorMessages", typeof(ServiceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request..
        /// </summary>
        internal static string BadGateway
        {
            get
            {
                return ResourceManager.GetString("BadGateway", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The condition specified in the conditional header(s) was not met for a write operation..
        /// </summary>
        internal static string ConditionNotMet
        {
            get
            {
                return ResourceManager.GetString("ConditionNotMet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value provided for one of the HTTP headers was not in the correct format..
        /// </summary>
        internal static string InvalidHeaderValue
        {
            get
            {
                return ResourceManager.GetString("InvalidHeaderValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One of the request inputs is not valid..
        /// </summary>
        internal static string InvalidInput
        {
            get
            {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An invalid value was specified for one of the query parameters in the request URI..
        /// </summary>
        internal static string InvalidQueryParameterValue
        {
            get
            {
                return ResourceManager.GetString("InvalidQueryParameterValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A required HTTP header was not specified..
        /// </summary>
        internal static string MissingRequiredHeader
        {
            get
            {
                return ResourceManager.GetString("MissingRequiredHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A required query parameter was not specified for this request..
        /// </summary>
        internal static string MissingRequiredQueryParameter
        {
            get
            {
                return ResourceManager.GetString("MissingRequiredQueryParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        internal static string None
        {
            get
            {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified resource already exists..
        /// </summary>
        internal static string ResourceAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("ResourceAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified resource does not exist..
        /// </summary>
        internal static string ResourceNotFound
        {
            get
            {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type..
        /// </summary>
        internal static string UnsupportedMediaType
        {
            get
            {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
    }
}
