//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.WorkOrders.Application.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationFailures
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationFailures()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.WorkOrders.Application.Resources.ValidationFailures", typeof(ValidationFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CreatedOn mandatory.
        /// </summary>
        public static string CreatedOnMandatory
        {
            get
            {
                return ResourceManager.GetString("CreatedOnMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits cannot be null or empty..
        /// </summary>
        public static string HandledUnitsCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits cannot contain null, but element at position [{Index}] is null..
        /// </summary>
        public static string HandledUnitsElemCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsElemCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits at position [{Index}] value for &apos;{Key}&apos; cannot be null or empty..
        /// </summary>
        public static string HandledUnitsElemKeyValueCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsElemKeyValueCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits at position [{Index}] has an invalid value for &apos;{Key}&apos; .
        /// </summary>
        public static string HandledUnitsElemKeyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsElemKeyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits Products cannot contain null, but element at position [{Index}].Products[{IndexProduct}] is null..
        /// </summary>
        public static string HandledUnitsProductsElemCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsProductsElemCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits at position  [{Index}].Products[{IndexProduct}] value for &apos;{Key}&apos; cannot be null or empty..
        /// </summary>
        public static string HandledUnitsProductsElemKeyValueCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsProductsElemKeyValueCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HandledUnits at position  [{Index}].Products[{IndexProduct}] has an invalid value for &apos;{Key}&apos; ..
        /// </summary>
        public static string HandledUnitsProductsElemKeyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("HandledUnitsProductsElemKeyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inputs cannot be null or empty..
        /// </summary>
        public static string InputsCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("InputsCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inputs cannot contain null, but element at position [{Index}] is null..
        /// </summary>
        public static string InputsElemCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("InputsElemCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inputs at position [{Index}] value for &apos;{Key}&apos; cannot be null or empty..
        /// </summary>
        public static string InputsElemKeyValueCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("InputsElemKeyValueCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inputs at position [{Index}] has an invalid value for &apos;{Key}&apos;..
        /// </summary>
        public static string InputsElemKeyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("InputsElemKeyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime.
        /// </summary>
        public static string InvalidDateTime
        {
            get
            {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operational mandatory.
        /// </summary>
        public static string OperationalMandatory
        {
            get
            {
                return ResourceManager.GetString("OperationalMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation mandatory.
        /// </summary>
        public static string OperationMandatory
        {
            get
            {
                return ResourceManager.GetString("OperationMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order mandatory.
        /// </summary>
        public static string OrderMandatory
        {
            get
            {
                return ResourceManager.GetString("OrderMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures cannot be null or empty..
        /// </summary>
        public static string PicturesCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("PicturesCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures cannot contain null, but element at position [{Index}] is null..
        /// </summary>
        public static string PicturesElemCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("PicturesElemCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures at position [{Index}] value for &apos;{Key}&apos; cannot be null or empty..
        /// </summary>
        public static string PicturesElemKeyValueCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("PicturesElemKeyValueCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures at position [{Index}] has an invalid value for &apos;{Key}&apos;..
        /// </summary>
        public static string PicturesElemKeyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("PicturesElemKeyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remarks cannot be null or empty..
        /// </summary>
        public static string RemarksCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("RemarksCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remarks cannot contain null, but element at position [{Index}] is null..
        /// </summary>
        public static string RemarksElemCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("RemarksElemCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remarks at position [{Index}] value for &apos;{Key}&apos; cannot be null or empty..
        /// </summary>
        public static string RemarksElemKeyValueCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("RemarksElemKeyValueCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remarks at position [{Index}] has an invalid value for &apos;{Key}&apos;..
        /// </summary>
        public static string RemarksElemKeyValueInvalid
        {
            get
            {
                return ResourceManager.GetString("RemarksElemKeyValueInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site mandatory.
        /// </summary>
        public static string SiteMandatory
        {
            get
            {
                return ResourceManager.GetString("SiteMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status should be a value of {0}.
        /// </summary>
        public static string StatusAllowedValues
        {
            get
            {
                return ResourceManager.GetString("StatusAllowedValues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status cannot be null or empty.
        /// </summary>
        public static string StatusCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("StatusCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Created mandatory.
        /// </summary>
        public static string UserCreatedMandatory
        {
            get
            {
                return ResourceManager.GetString("UserCreatedMandatory", resourceCulture);
            }
        }
    }
}
